[metadata]
name = stressberry
version = 0.3.3
author = Nico Schlömer
author_email = nico.schloemer@gmail.com
description = Stress tests for the Raspberry Pi
url = https://github.com/nschloe/stressberry
project_urls =
    Code=https://github.com/nschloe/stressberry
    Issues=https://github.com/nschloe/stressberry/issues
    Funding=https://github.com/sponsors/nschloe
long_description = file: README.md
long_description_content_type = text/markdown
license = GPL-3.0-or-later
classifiers =
    Development Status :: 4 - Beta
    License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)
    Operating System :: OS Independent
    Programming Language :: Python
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    Topic :: Utilities

[options]
packages = find:
install_requires =
    matplotlib
    matplotx
    pyyaml
python_requires = >=3.11

[options.entry_points]
console_scripts =
    stressberry-run = stressberry.cli:run
    stressberry-plot = stressberry.cli:plot
